# Generated by Django 4.2.6 on 2023-11-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_image_employees_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
