# Generated by Django 4.2.6 on 2023-11-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_profile_pic_employees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
